language: php

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files

php:
  - 7.0
  - 7.1.3

env:
  - TESTBENCH_VERSION=~3.5.0
  - TESTBENCH_VERSION=~3.6.0 COVERAGE=true

matrix:
  exclude:
    - php: 7.0
      env: TESTBENCH_VERSION=~3.6.0 COVERAGE=true

before_install:
  #  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - phpenv config-rm xdebug.ini
  - composer global require hirak/prestissimo --update-no-dev
  - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --prefer-dist

install: travis_retry composer install --no-interaction --prefer-dist

before_script: phpenv config-add ~/xdebug.ini

script:
  - composer show
  - vendor/bin/phpunit -v

after_success: sh -c "if [ ! -z ${COVERAGE+x} ]; then php vendor/bin/php-coveralls; fi"

notifications:
  email: false